### ISSUE TITLE
Point to @miragejs/server?

### ISSUE THREAD

**Issue by samselikoff** [cowboyd/mirage-server#10]
Hey hey friends!

Wondering if y'all are finished working on this repo, could we add a message to it that points to https://github.com/miragejs/server? Now that we finally got around to the port :)

Also, if there's any breaking changes from here to there that your users run into, I wouldn't want to leave them behind. I don't think there should be anything though.

Thanks for this cow path & motivating me to work on generalizing Mirage!

**Comment by cowboyd** [comment]
Hey @samselikoff! Now worries! I'm pointing this repo to miragejs/server as suggested and archiving it. Thanks!
