### ISSUE TITLE
[question]  Does it override the native HTTP request?

### ISSUE THREAD

**Issue by quantuminformation** [cowboyd/mirage-server#3]
Firstly, thanks so much for your efforts on this.

When this is used in Ember cli, the get requests know when to use mirage, how does this work in a vanilla or react app? Does it override the native HTTP request?

**Comment by ahx** [comment]
@QuantumInformation mirage-server uses [pretender](https://github.com/pretenderjs/pretender) under the hood. "Pretender will temporarily replace the native XMLHttpRequest object, intercept all requests, and direct them to little pretend service you've defined." AFAIK This happens as soon as you define the server via `new MirageServer` and stop when you call `shutdown`, which should be the same like [pretender's `shutdown`](https://github.com/pretenderjs/pretender#clean-up)

**Comment by quantuminformation** [comment]
Cool thx, I thought so.
