### ISSUE TITLE
Anyone using this and is it being maintained with latest mirage?

### ISSUE THREAD

**Issue by quantuminformation** [cowboyd/mirage-server#7]

**Comment by samselikoff** [comment]
Hey @QuantumInformation , I've finally extracted Mirage.js from Ember CLI Mirage and you can follow along over here: https://github.com/miragejs/server

The docs are a wip but you can find them here: https://miragejs.com/docs/getting-started/introduction/

**Comment by quantuminformation** [comment]
Awesome thanks, if I use it I will let you know!
