### ISSUE TITLE
How tricky was this extraction?

### ISSUE THREAD

**Issue by samselikoff** [cowboyd/mirage-server#8]
👋 Hey there @cowboyd!

I wanted to show some folks Mirage in Vue/React projects, so was thinking of doing a spike on getting current Mirage working outside of Ember. Figured I'd drop by and ask if you had any tips or tricks that you learned going through this process last year.

Hope all is well!

**Comment by quantuminformation** [comment]
Mirage would be so good in Vue and especially react for me.

**Comment by cowboyd** [comment]
The latest repo has moved over here https://github.com/bigtestjs/mirage

It was actually pretty straight forward. The hardest parts were 

1. migrating the test suite over to karma. That was the first step, and once it was working, we just followed the path that the test laid out.
2. I remember getting rid of Ember inflector and using a non-ember library was a challenge.

By the way, you're welcome to use the fork as a starting point. A you can see, we maintained the entire Mirage commit history!

@QuantumInformation We have used mirage in several React projects now with great success, and I'd be happy to walk you through it. Unfortunately we haven't yet written up a guide. Here is an example of one of them https://github.com/folio-org/ui-eholdings/tree/master/test/bigtest/network
